# Data and Plots for Competitive Adsorption Between Nitrogen and Hydrogen

In [1]:
import grand_canonical as gc
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

In [2]:
#Set global parameters

size = 4
n_steps = 10000
mus_A = np.linspace(-0.2, 0, 7)
Ts = np.linspace(0.001, 0.019, 7)

## Parameter set 1: Ideal mixture of nitrogen and hydrogen

In [3]:
#Set parameters


params_1 = []
for mu_A in mus_A:
    for T in Ts:
        params_1.append({
            'epsilon_A': -0.1,
            'epsilon_B': -0.1,
            'epsilon_AA': 0,
            'epsilon_BB': 0,
            'epsilon_AB': 0,
            'mu_A': mu_A,
            'mu_B': -0.1,
            'T': T  # Temperature (in units of k)
        })

In [4]:
#Run the simulation

ps1_fl = np.zeros((len(mus_A), len(Ts), size, size))    #Initialize final lattice
mc1_A = np.zeros((len(mus_A), len(Ts))) #Initialize lattice for mean coverage of particle A
mc1_B = np.zeros((len(mus_A), len(Ts))) #Initialize lattice for mean coverage of particle B

for i, param in enumerate(params_1):
    lattice, coverage_A, coverage_B = gc.run_simulation(size, n_steps, param)
    ps1_fl[i // len(Ts), i % len(Ts)] = lattice
    mc1_A[i // len(Ts), i % len(Ts)] = np.mean(coverage_A[-1000:])
    mc1_B[i // len(Ts), i % len(Ts)] = np.mean(coverage_B[-1000:])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
N_empty: 16
0 0
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
N_empty: 16
0 0
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
N_empty: 16
0 0
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
N_empty: 15
0 1
[[2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
[[0. 0. 0. 0.]
 [2. 2. 2. 2.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
N_empty: 16
0 0
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
[[0. 0. 0. 0.]
 [2. 2. 2. 2.]
 [0. 0. 0. 0.]
 [2. 2. 2. 2.]]
N_empty: 15
0 1
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]]


ValueError: high <= 0

## Parameter set 2: Repulsive interactions between nitrogen and hydrogen

In [10]:
#Set parameters


params_2 = []
for mu_A in mus_A:
    for T in Ts:
        params_2.append({
            'epsilon_A': -0.1,
            'epsilon_B': -0.1,
            'epsilon_AA': 0.05,
            'epsilon_BB': 0.05,
            'epsilon_AB': 0.05,
            'mu_A': mu_A,
            'mu_B': -0.1,
            'T': T  # Temperature (in units of k)
        })

## Parameter set 3: Attractive interactions between nitrogen and hydrogen

In [11]:
#Set parameters


params_3 = []
for mu_A in mus_A:
    for T in Ts:
        params_3.append({
            'epsilon_A': -0.1,
            'epsilon_B': -0.1,
            'epsilon_AA': -0.05,
            'epsilon_BB': -0.05,
            'epsilon_AB': -0.05,
            'mu_A': mu_A,
            'mu_B': -0.1,
            'T': T  # Temperature (in units of k)
        })

## Parameter set 4: Immiscible nitrogen and hydrogen

In [12]:
#Set parameters


params_4 = []
for mu_A in mus_A:
    for T in Ts:
        params_4.append({
            'epsilon_A': -0.1,
            'epsilon_B': -0.1,
            'epsilon_AA': -0.05,
            'epsilon_BB': -0.05,
            'epsilon_AB': 0.05,
            'mu_A': mu_A,
            'mu_B': -0.1,
            'T': T  # Temperature (in units of k)
        })

## Parameter set 5: "Like dissolves unlike" scenario

In [13]:
#Set parameters


params_5 = []
for mu_A in mus_A:
    for T in Ts:
        params_5.append({
            'epsilon_A': -0.1,
            'epsilon_B': -0.1,
            'epsilon_AA': 0.05,
            'epsilon_BB': 0.05,
            'epsilon_AB': -0.05,
            'mu_A': mu_A,
            'mu_B': -0.1,
            'T': T  # Temperature (in units of k)
        })